'use strict';
const $=s=>document.querySelector(s), form=$('#report-form');
const todayKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fmt=(v)=>{if(!v)return '—';const d=new Date(String(v).length===10?v+'T00:00:00+08:00':v);return isNaN(d)?String(v):new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Makassar'}).format(d)};
const dayKey=v=>{const d=new Date(String(v).length===10?v+'T00:00:00+08:00':v);return isNaN(d)?'':new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
let reports=[],loaded=false,loading=false,saving=false,processing=false,dirty=false,photoData=[],photoToken=0,lastSaved=null;
const required=[...form.querySelectorAll('[name][required]')];
$('#today').textContent=new Intl.DateTimeFormat('id-ID',{weekday:'short',day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Makassar'}).format(new Date());
$('#metric-date').textContent=fmt(todayKey());form.elements.visitDate.value=todayKey();
function progress(){
 const hasDoc=photoData.length>=1&&photoData.length<=10;
 const total=required.length+1,n=required.filter(el=>el.value.trim()&&el.checkValidity()).length+(hasDoc?1:0);
 $('#progress').value=n;$('#progress-percent').textContent=Math.round(n/total*100)+'%';$('#progress-count').textContent=n+' dari '+total+' kolom wajib';$('#progress').max=total;$('#form-state').textContent=dirty?'Ada isian yang belum disimpan':'Belum ada perubahan';
}

function showView(view){$('#form-view').hidden=view!=='form';$('#history-view').hidden=view!=='history';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent=view==='form'?'Laporan kegiatan':'Riwayat laporan';$('#page-subtitle').textContent=view==='form'?'Setiap kunjungan, tercatat dengan baik.':'Identitas dan laporan kasus dibuka menggunakan PIN.';if(view==='history')loadReports();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
form.addEventListener('input',()=>{dirty=true;progress()});
window.addEventListener('beforeunload',e=>{if(dirty||saving){e.preventDefault();e.returnValue=''}});
async function modal(options){if(window.Swal)return Swal.fire({confirmButtonColor:'#195ddd',cancelButtonColor:'#748498',...options});if(options.showCancelButton)return {isConfirmed:window.confirm(options.title+'\n'+(options.text||''))};window.alert(options.title+'\n'+(options.text||''));return {isConfirmed:true}}
function renderPhotos(){
 const gallery=$('#photo-gallery');gallery.replaceChildren();$('#photo-count').textContent=photoData.length+' dari 10 foto';
 photoData.forEach((photo,index)=>{const card=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption'),remove=document.createElement('button');img.src=photo.data;img.alt='Dokumentasi '+(index+1);caption.textContent=(index+1)+'. '+photo.name;remove.type='button';remove.className='text-button';remove.textContent='Hapus foto';remove.disabled=processing||saving;remove.onclick=()=>{if(processing||saving)return;photoData.splice(index,1);dirty=true;renderPhotos();progress();};card.append(img,caption,remove);gallery.append(card)});
 $('#photo').disabled=processing||saving||photoData.length>=10;
}
function clearPhoto(){photoToken++;photoData=[];$('#photo').value='';$('#photo-error').textContent='';processing=false;$('#save').disabled=saving;renderPhotos();progress();}

function resetForm(){HTMLFormElement.prototype.reset.call(form);form.elements.visitDate.value=todayKey();clearPhoto();dirty=false;progress();}
$('#clear-form').onclick=async()=>{if(dirty){const r=await modal({icon:'question',title:'Kosongkan formulir?',text:'Isian yang belum disimpan akan dihapus.',showCancelButton:true,confirmButtonText:'Ya, kosongkan',cancelButtonText:'Kembali'});if(!r.isConfirmed)return}resetForm();$('#save-message').hidden=true};
async function compressPhoto(file){
 const url=URL.createObjectURL(file);
 try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,900/Math.max(img.width,img.height));const canvas=document.createElement('canvas');let width=Math.max(1,Math.round(img.width*scale)),height=Math.max(1,Math.round(img.height*scale));
 for(let step=0;step<5;step++){canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(img,0,0,width,height);for(const quality of [.8,.65,.5,.35,.2]){const data=canvas.toDataURL('image/jpeg',quality);if(data.length<=45000)return {name:file.name,data};}width=Math.max(1,Math.round(width*.7));height=Math.max(1,Math.round(height*.7));}
 throw new Error('Foto terlalu kompleks. Pilih foto berukuran lebih kecil.');
 }finally{URL.revokeObjectURL(url)}
}
async function selectPhotos(files){
 if(processing||saving)return;const selected=Array.from(files||[]);if(!selected.length)return;const error=$('#photo-error');error.textContent='';$('#photo').value='';
 if(photoData.length+selected.length>10){error.textContent='Maksimal 10 foto. Anda masih dapat menambah '+(10-photoData.length)+' foto.';return}
 if(selected.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type))){error.textContent='Semua berkas harus berupa foto JPG, PNG, atau WEBP.';return}
 if(selected.some(f=>f.size>5*1024*1024)){error.textContent='Ukuran setiap foto maksimal 5 MB.';return}
 processing=true;const token=++photoToken;$('#save').disabled=true;$('#clear-form').disabled=true;renderPhotos();
 try{const added=[];for(let i=0;i<selected.length;i++){error.textContent='Menyiapkan foto '+(i+1)+' dari '+selected.length+'…';added.push(await compressPhoto(selected[i]));if(token!==photoToken)return}photoData.push(...added);dirty=true;error.textContent='';}
 catch(e){error.textContent=e.message||'Foto tidak dapat dibaca. Pilih ulang foto.';}
 finally{if(token===photoToken){processing=false;$('#save').disabled=saving;$('#clear-form').disabled=saving;renderPhotos();progress()}}
}
$('#photo').onchange=e=>selectPhotos(e.target.files);const zone=$('#dropzone');['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>selectPhotos(e.dataTransfer.files));
function normalized(r){return {...r,patientName:String(r.patientName??''),visitCluster:String(r.visitCluster??''),visitDate:r.visitDate??''}}
function renderReports(){let items=reports.filter(r=>[r.patientName,r.visitCluster].join(' ').toLowerCase().includes($('#search').value.trim().toLowerCase())&&(!$('#date-filter').value||dayKey(r.visitDate)===$('#date-filter').value));items.sort((a,b)=>String(b.createdAt||b.visitDate).localeCompare(String(a.createdAt||a.visitDate)));$('#report-rows').replaceChildren();$('#result-count').textContent=items.length+' dari '+reports.length+' laporan';$('#table-wrap').hidden=!items.length;$('#history-state').hidden=!!items.length;
 if(!items.length)$('#history-state').textContent=loaded?(reports.length?'Tidak ada laporan yang sesuai pencarian.':'Belum ada laporan. Buat laporan kunjungan pertama Anda.'):'Laporan belum dapat dimuat. Periksa koneksi database, lalu klik Perbarui.';
 items.forEach(r=>{const tr=document.createElement('tr');const date=document.createElement('td');date.textContent=fmt(r.visitDate);const patient=document.createElement('td');const name=document.createElement('strong');name.textContent=r.patientName||'—';const nik=document.createElement('small');nik.textContent='Identitas dilindungi PIN';patient.append(name,nik);const diagnosis=document.createElement('td');diagnosis.textContent=r.visitCluster||'—';const doc=document.createElement('td');doc.textContent=r.documentation?'Terlampir':'—';const action=document.createElement('td');const btn=document.createElement('button');btn.className='text-button';btn.textContent='Lihat detail ↗';btn.onclick=()=>unlockDetail(r);action.append(btn);tr.append(date,patient,diagnosis,doc,action);$('#report-rows').append(tr)});
}
async function loadReports(){if(loading||saving)return;loading=true;$('#refresh').disabled=true;$('#retry').disabled=true;if(!loaded)$('#status').textContent='Menghubungkan…';try{const d=await ReportAPI.request();reports=d.data.map(normalized);loaded=true;$('#total').textContent=reports.length;$('#nav-count').textContent=reports.length;$('#today-count').textContent=reports.filter(r=>dayKey(r.visitDate)===todayKey()).length;$('#status').textContent='Terhubung';$('#status').style.color='#168173';$('#sync-time').textContent='Diperbarui '+new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Makassar'}).format(new Date())+' WITA';$('#connection-error').hidden=true;renderReports();}catch(e){$('#status').textContent=loaded?'Sinkronisasi tertunda':'Belum terhubung';$('#status').style.color='#a66622';$('#connection-error').hidden=false;$('#connection-message').textContent=(e.name==='TypeError'?'Tidak dapat membaca respons server. Periksa koneksi, izin, dan deployment Apps Script.':e.message)+(loaded?' Data yang terlihat berasal dari sinkronisasi terakhir.':'');if(!loaded)renderReports();}finally{loading=false;$('#refresh').disabled=false;$('#retry').disabled=false;}}
$('#retry').onclick=loadReports;$('#refresh').onclick=loadReports;$('#search').oninput=renderReports;$('#date-filter').onchange=renderReports;
const labels={visitCluster:'Kunjungan',visitDate:'Tanggal Kunjungan',patientName:'Nama Pasien',caseReport:'Laporan Kasus',followUpResult:'Hasil Tindak Lanjut',documentation:'Dokumentasi'};
async function unlockDetail(summary){
 if(!window.Swal){window.alert('Form PIN belum dapat dimuat. Muat ulang halaman.');return}
 const result=await Swal.fire({title:'Masukkan PIN',text:'PIN diperlukan untuk melihat detail laporan.',input:'password',inputLabel:'PIN akses laporan',inputAttributes:{inputmode:'numeric',maxlength:'6',autocomplete:'off'},showCancelButton:true,confirmButtonText:'Buka detail',cancelButtonText:'Batal',confirmButtonColor:'#195ddd',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),preConfirm:async pin=>{if(!/^\d{6}$/.test(pin)){Swal.showValidationMessage('Masukkan 6 digit PIN.');return false}try{return (await ReportAPI.detail(summary.id,pin)).data}catch(e){Swal.showValidationMessage(e.message);return false}}});
 if(result.isConfirmed&&result.value)detail(result.value);
}
function detail(r){$('#detail-name').textContent=r.patientName||'Laporan pasien';$('#detail-content').replaceChildren();for(const [key,label]of Object.entries(labels)){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;const v=r[key];dd.textContent=key==='visitDate'?fmt(v):String(v??'—')||'—';if(key==='documentation'){dd.replaceChildren();dd.className='detail-photos';const photos=Array.isArray(v)?v:[v];photos.filter(v=>typeof v==='string'&&/^data:image\/(jpeg|png|webp);base64,/.test(v)).forEach((src,index)=>{const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=src;img.alt='Dokumentasi '+(index+1);caption.textContent='Foto '+(index+1);figure.append(img,caption);dd.append(figure)});if(!dd.childElementCount)dd.textContent='Tidak ada foto yang dapat ditampilkan.';}div.append(dt,dd);$('#detail-content').append(div)}$('#detail').showModal()}
$('#close-detail').onclick=()=>$('#detail').close();
$('#detail').addEventListener('close',()=>{$('#detail-content').replaceChildren();$('#detail-name').textContent=''});
form.addEventListener('submit',async e=>{e.preventDefault();if(saving||processing)return;if(!form.reportValidity())return;const payload={};for(const el of form.querySelectorAll('[name]')){payload[el.name]=el.value.trim();if(el.required&&!payload[el.name]){el.setCustomValidity('Kolom ini wajib diisi.');el.reportValidity();el.oninput=()=>el.setCustomValidity('');return}}payload.documentation=photoData.map(p=>p.data);if(payload.documentation.length<1||payload.documentation.length>10){$('#photo-error').textContent='Dokumentasi wajib diisi dengan 1–10 foto.';$('#photo').focus();return}const fingerprint=JSON.stringify(payload);if(fingerprint===lastSaved){await modal({icon:'info',title:'Laporan ini sudah disimpan',text:'Ubah isian untuk membuat laporan baru.'});return}
 saving=true;$('#fields').disabled=true;$('#save').disabled=true;$('#clear-form').disabled=true;renderPhotos();$('#save').textContent='Menyimpan…';$('#save-message').hidden=true;
 let confirmed=false;
 try{await ReportAPI.request(payload);confirmed=true;lastSaved=fingerprint;dirty=false;resetForm();$('#save-message').textContent='Laporan berhasil disimpan ke database Google Sheets.';$('#save-message').hidden=false;await modal({icon:'success',title:'Laporan berhasil disimpan',text:'Data laporan kegiatan telah berhasil disimpan ke database Google Sheets.',confirmButtonText:'Selesai'});}catch(err){if(confirmed){$('#save-message').hidden=false;$('#save-message').textContent='Data sudah tersimpan. Buka riwayat untuk melihat laporan.';await modal({icon:'success',title:'Laporan berhasil disimpan',text:'Data sudah masuk ke database. Tampilan formulir belum dapat diperbarui; jangan kirim ulang laporan ini.',confirmButtonText:'Selesai'});}else{$('#save-message').hidden=false;$('#save-message').textContent='Penyimpanan belum terkonfirmasi. Isian tetap tersedia. Periksa riwayat sebelum mengirim ulang untuk menghindari duplikasi.';await modal({icon:'error',title:'Penyimpanan belum terkonfirmasi',text:err.message+' Isian Anda tetap tersedia. Periksa riwayat sebelum mengirim ulang.',confirmButtonText:'Kembali ke formulir'});}}finally{saving=false;$('#fields').disabled=false;$('#save').disabled=processing;$('#clear-form').disabled=false;renderPhotos();$('#save').innerHTML='Simpan laporan <span>↗</span>';loadReports();}
});
progress();loadReports();setInterval(()=>{if(!document.hidden)loadReports()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadReports()});
